name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
   group: ci-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

env:
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

jobs:
  setup:
    name: 'Setup'
    runs-on: ubuntu-latest
    outputs:
      pending: ${{ steps.set-pending.outputs.pend }}
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm build

  # debug_pending_tasks:
  #   runs-on: ubuntu-latest
  #   needs: [setup]
  #   steps:
  #     - run: echo ${{  needs.setup.outputs.pending }}
  #     - run: echo '${{  needs.setup.outputs.pending }}' | jq
  #     - run: echo '${{  fromJSON(needs.setup.outputs.pending).atAll.lint }}'

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [setup]
    # if: ${{ fromJSON(needs.setup.outputs.pending).atAll.lint }}
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm lint


  test:
    name: "Default Tests"
    runs-on: ubuntu-latest
    needs: [setup]
    # if: ${{ fromJSON(needs.setup.outputs.pending).atAll.test }}
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: pnpm turbo test --filter test-app

  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    needs: [test]
    # if: ${{ fromJSON(needs.setup.outputs.pending).atAll.test }}
    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pnpm-args: --no-lockfile
      - run: pnpm turbo test --filter test-app

  try-scenarios:
    name: "${{ matrix.try-scenario }} ${{ matrix.test-app == 'test-app' && '(Classic)' || '(Embroider)' }}"
    runs-on: ubuntu-latest
    needs: [test]
    # if: ${{ fromJSON(needs.setup.outputs.pending).atAll.test }}
    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-3.28
          - ember-lts-4.4
          - ember-lts-4.8
          - ember-lts-4.12
          - ember-5.0
          - ember-release
          - ember-beta
          - ember-canary
        test-app:
          - test-app
          - test-embroider-app

    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests
        run: pnpm turbo test:scenario --filter ${{ matrix.test-app }} --log-prefix none -- --skip-cleanup
        env:
          SCENARIO: ${{ matrix.try-scenario }}

  typecheck:
    name: '${{ matrix.typescript-scenario }}'
    runs-on: ubuntu-latest
    # if: ${{ fromJSON(needs.setup.outputs.pending).atAll.typecheck }}
    timeout-minutes: 2
    needs: [test]
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        typescript-scenario:
          - typescript@4.8
          - typescript@4.9
          - typescript@5.0
          - typescript@rc
          - typescript@next

    steps:
      - uses: wyvox/action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Change TS to ${{ matrix.typescript-scenario }}'
        run: 'pnpm add --save-dev ${{ matrix.typescript-scenario}}'
        working-directory: ./test-app
      - name: 'Type checking'
        run: pnpm turbo --filter 'test-app' lint:types

