name: Lint

on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - master

env:
  CI: true

jobs:
  source:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Source
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install --frozen-lockfile

      - name: ESLint
        run: yarn lint:js

      - name: Templates
        run: yarn lint:hbs


  # docs:
  #   if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
  #   name: Docs
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: volta-cli/action@v1
  #   - uses: actions/cache@v2
  #     with:
  #       path: '**/node_modules'
  #       key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
  #   - run: yarn lint:docs


  # docs-js-code:
  #   if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
  #   name: Docs (JS Code Samples)
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: volta-cli/action@v1
  #   - uses: actions/cache@v2
  #     with:
  #       path: '**/node_modules'
  #       key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
  #   - run: yarn lint:docs-js

  commits:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    name: Commit Messages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: volta-cli/action@v1
    - uses: wagoid/commitlint-github-action@v2.2.2
