name: Quality

on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - master

env:
  CI: true
  CACHE_PATH: '**/node_modules'
  LIBRARY_DIR: './ember-data-resources'
  TEST_DIR: './test-app'

concurrency:
   group: quality-${{ github.head_ref || github.ref }}
   cancel-in-progress: true

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2.1.7
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: "${{ runner.os }}-modules-"
      - run: yarn install

  source:
    name: Source
    runs-on: ubuntu-latest
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2.1.7
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install

      - name: ESLint
        run: |
          cd ${{ env.LIBRARY_DIR }}
          yarn lint:js

  test_app:
    name: Test App
    runs-on: ubuntu-latest
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2.1.7
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install

      - name: ESLint
        run: |
          cd ${{ env.TEST_DIR }}
          yarn lint:js

      - name: Type Checking
        run: |
          cd ${{ env.TEST_DIR }}
          yarn tsc --build

  tooling:
    name: Tooling
    runs-on: ubuntu-latest
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - uses: actions/cache@v2.1.7
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: yarn install
      - name: Semantic Release
        run: |
          cd ${{ env.LIBRARY_DIR }}
          yarn semantic-release --dry-run
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # docs:
  #   if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
  #   name: Docs
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: volta-cli/action@v1

  #   - run: yarn install
  #   - run: yarn lint:docs


  # docs-js-code:
  #   if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
  #   name: Docs (JS Code Samples)
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: volta-cli/action@v1

  #   - run: yarn install
  #   - run: yarn lint:docs-js

  commits:
    name: Commit Messages
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: volta-cli/action@v1
    - uses: wagoid/commitlint-github-action@v4.1.9
